### ISSUE TITLE
Unexpected Variable font behaviour around Axis Defaults

### ISSUE THREAD

**Issue by rp118758** [typemytype/drawbot#305]
When generating proofing pdfs for a variable font at different locations in the designspace, the default location is frequently displaying as the minimum value for a given axis. 

For example, a font with the axes below may return correctly at (wght=500, wdth=101) and (wght=500, wdth=99) but effectively display (wght=500, wdth=75) when passed (wght=500, wdth=100).

This is replicable with the trial versions of [Grtsk](https://black-foundry.com/fonts/grtsk/) and [Venn](https://www.daltonmaag.com/library/venn).

```newPage()
font('TRYGrtskVariable')

for axis, data in listFontVariations().items():
    print((axis, data))
    
fontSize(180)
fontVariations(wght=400, wdth=299, slnt=0)
text('Test', (100,734))

fontVariations(wght=400, wdth=300, slnt=0)
text('Test', (100,538))

fontVariations(wght=400, wdth=301, slnt=0)
text('Test', (100,356))
```
![image](https://user-images.githubusercontent.com/15689232/66045381-87fea100-e51b-11e9-9ca3-a547c736dc65.png)

**Comment by justvanrossum** [comment]
I've observed this as well. I may be an OS issue. On which OS are you?

**Comment by rp118758** [comment]
macOS Mojave, v. 10.14.5

**Comment by justvanrossum** [comment]
Anyone here able to see whether this issue still exists on 10.15?

https://twitter.com/jjgod/status/1179892274487906304

**Comment by justvanrossum** [comment]
Presumably this has been fixed on 10.15. Let's keep this open until we know for sure.

**Comment by justvanrossum** [comment]
See also this Twitter thread: https://twitter.com/jenskutilek/status/1197128145683566592

**Comment by typemytype** [comment]
this seems to be fixed on 10.15


<img width="1312" alt="Schermafbeelding 2019-11-30 om 21 15 10" src="https://user-images.githubusercontent.com/1190358/69905615-871cab00-13b6-11ea-86be-d34408f0991d.png">

**Comment by arrowtype** [comment]
Did anyone make any changes to the DrawBot code to fix this issue (e.g. shifting values by minute amounts to work around the issue)? I still experience similar problems in Sketch on macOS 10.15, but haven't had the problem in DrawBot, recently.

![image](https://user-images.githubusercontent.com/45946693/74769340-3bacc700-5258-11ea-9d85-508d675da745.png)

![image](https://user-images.githubusercontent.com/45946693/74769549-9c3c0400-5258-11ea-8395-64d8e5a647ad.png)

Versus Sketch:

![image](https://user-images.githubusercontent.com/45946693/74769573-a9f18980-5258-11ea-9559-0aad33fe195a.png)

As far as I know, both DrawBot and Sketch use Core Text (native macOS text rendering). Is this correct for DrawBot? If so, is there some kind of reason you can guess that this would work in DrawBot, but not in Sketch? Just hoping to update reports with Apple & Sketch to get this resolved, if possible. :)

**Comment by typemytype** [comment]
there where no changed made to fix this issue inside DrawBot, I assume its been fixed in the os/CoreText.
